blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/your-username/will-save-the-transcriber/discussions
    about: Please ask and answer questions here. 